#
# From http://svn.openmoko.org/trunk/gta02-core/components/
#
# Note that we don't have the concept of a "library of everything" so far.
#

.PHONY:		all sch

all:		sch

#		@echo "make what ? targets: sch loe"
#		@exit 1

sch:
		eeschema `pwd`/components.sch

#loe:
#		./mkloe
